### ISSUE TITLE
Fail to create new version after upgrade to 4.1 (from 3.14) - renaming form destination #214

### ISSUE THREAD

**Issue by ben-dw** [matomo-org/tag-manager#297]
I'd like to create a new version after upgrading from Matomo 3.14 to 4.1. But there is a bug:
![matomo-form-destination-bug](https://user-images.githubusercontent.com/43407231/105319770-9d428780-5bc5-11eb-8130-843256d4b801.png)

Trigger conditions are not renamed if there are some existing:
![Bildschirmfoto 2021-01-21 um 08 28 32](https://user-images.githubusercontent.com/43407231/105320034-fa3e3d80-5bc5-11eb-9a86-97ccb5801e09.png)

Bug is described in #214 and fixed in #215

**Comment by tsteur** [comment]
@ben-dw sorry about that. There should have been an update script to correct this. Can you select the correct value there as it was renamed?

**Comment by ben-dw** [comment]
@tsteur That's the way how I fixed it ;-)
Just wanted to let you know and maybe otherones who have the same issue with "FormDestionation".

**Comment by tsteur** [comment]
Thanks @ben-dw very appreciated. I'll close this for now as it's answered and we'll keep this in mind for next time 👍

**Comment by rabbit28399** [comment]
Hello, 

I am still having this problem on Matomo 4.6.
Could you tell me how to solve this? 

Thank you.

**Comment by ben-dw** [comment]
@vonnyp you have to change your triggers/variables and select "FormDestination" before you are able to create a new version.
